/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 90degreeswest.com (https://sketchfab.com/90degreeswest.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lotus-slow-07a88cb8890e4237b93e5778bcf9ac9b
Title: Lotus Slow
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import model from "../../assets/cosmic/lotus_slow.glb";

export function Lotus(props) {
  const ref = useRef();
  const { nodes, materials, animations } = useGLTF(model);
  const { actions } = useAnimations(animations, ref);

  useEffect(() => {
    console.log(actions);
    actions["CINEMA_4D_Main"].play();
  });

  return (
    <group ref={ref} scale={0.05} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="3e65f8e8221f4002ada4cd12d8c04689fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Lotus_Shader" position={[27.516, 37.103, 5.012]} />
                <group name="Shader" position={[0, 29.386, 0]} />
                <group name="Stamen">
                  <group
                    name="Stamen_2"
                    position={[-0.148, -1.819, -76.445]}
                    rotation={[Math.PI, 0.081, -Math.PI]}
                  />
                </group>
                <group
                  name="Reference_Geo"
                  position={[0, 22.26, 0.86]}
                  rotation={[-Math.PI, 0, 0]}
                />
                <group
                  name="RS_Camera"
                  position={[267.596, 128.255, 145.555]}
                  rotation={[-Math.PI, 0.466, 2.854]}
                >
                  <group name="Object_10" />
                </group>
                <group
                  name="RS_Area_Light_2"
                  position={[-63.098, 235.063, 95.907]}
                  rotation={[-1.183, -0.244, -0.534]}
                >
                  <group name="Light">
                    <group name="Object_13" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_14" />
                    </group>
                  </group>
                </group>
                <group
                  name="RS_Area_Light_1"
                  position={[-238.221, 255.32, -212.244]}
                  rotation={[-2.264, -0.622, -2.53]}
                >
                  <group name="Light_2">
                    <group name="Object_17" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_18" />
                    </group>
                  </group>
                </group>
                <group
                  name="RS_Area_Light"
                  position={[155.92, 190.923, 7.587]}
                  rotation={[-1.531, 0.684, 1.508]}
                >
                  <group name="Light_3">
                    <group name="Object_21" rotation={[Math.PI / 2, 0, 0]}>
                      <group name="Object_22" />
                    </group>
                  </group>
                </group>
                <group name="RS_Dome_Light" />
                <group name="Lotus_Animate">
                  <group
                    name="Cloner_1"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0"
                      position={[0, 0, -7]}
                      rotation={[-1.256, -0.005, -0.278]}
                      scale={0.413}
                    >
                      <group name="New_Petal_0_2">
                        <mesh
                          name="New_Petal_0_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1"
                      position={[4.95, 0, -4.95]}
                      rotation={[-1.348, -0.225, -1.039]}
                      scale={0.413}
                    >
                      <group name="New_Petal_1_2">
                        <mesh
                          name="New_Petal_1_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2"
                      position={[7, 0, 0]}
                      rotation={[-1.576, -0.315, -1.851]}
                      scale={0.413}
                    >
                      <group name="New_Petal_2_2">
                        <mesh
                          name="New_Petal_2_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3"
                      position={[4.95, 0, 4.95]}
                      rotation={[-1.801, -0.217, -2.661]}
                      scale={0.413}
                    >
                      <group name="New_Petal_3_2">
                        <mesh
                          name="New_Petal_3_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4"
                      position={[0, 0, 7]}
                      rotation={[-1.886, 0.005, 2.863]}
                      scale={0.413}
                    >
                      <group name="New_Petal_4_2">
                        <mesh
                          name="New_Petal_4_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5"
                      position={[-4.95, 0, 4.95]}
                      rotation={[-1.793, 0.225, 2.102]}
                      scale={0.413}
                    >
                      <group name="New_Petal_5_2">
                        <mesh
                          name="New_Petal_5_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6"
                      position={[-7, 0, 0]}
                      rotation={[-1.565, 0.315, 1.291]}
                      scale={0.413}
                    >
                      <group name="New_Petal_6_2">
                        <mesh
                          name="New_Petal_6_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7"
                      position={[-4.95, 0, -4.95]}
                      rotation={[-1.341, 0.217, 0.481]}
                      scale={0.413}
                    >
                      <group name="New_Petal_7_2">
                        <mesh
                          name="New_Petal_7_2__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_2__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_2"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_3"
                      position={[0, 0, -7]}
                      rotation={[-0.712, -0.013, -0.273]}
                      scale={0.637}
                    >
                      <group name="New_Petal_0_4">
                        <mesh
                          name="New_Petal_0_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_3"
                      position={[4.95, 0, -4.95]}
                      rotation={[-0.893, -0.576, -0.856]}
                      scale={0.637}
                    >
                      <group name="New_Petal_1_4">
                        <mesh
                          name="New_Petal_1_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_3"
                      position={[7, 0, 0]}
                      rotation={[-1.591, -0.859, -1.859]}
                      scale={0.637}
                    >
                      <group name="New_Petal_2_4">
                        <mesh
                          name="New_Petal_2_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_3"
                      position={[4.95, 0, 4.95]}
                      rotation={[-2.266, -0.554, -2.841]}
                      scale={0.637}
                    >
                      <group name="New_Petal_3_4">
                        <mesh
                          name="New_Petal_3_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_3"
                      position={[0, 0, 7]}
                      rotation={[-2.43, 0.013, 2.868]}
                      scale={0.637}
                    >
                      <group name="New_Petal_4_4">
                        <mesh
                          name="New_Petal_4_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_3"
                      position={[-4.95, 0, 4.95]}
                      rotation={[-2.249, 0.576, 2.285]}
                      scale={0.637}
                    >
                      <group name="New_Petal_5_4">
                        <mesh
                          name="New_Petal_5_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_3"
                      position={[-7, 0, 0]}
                      rotation={[-1.551, 0.859, 1.282]}
                      scale={0.637}
                    >
                      <group name="New_Petal_6_4">
                        <mesh
                          name="New_Petal_6_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_3"
                      position={[-4.95, 0, -4.95]}
                      rotation={[-0.876, 0.554, 0.301]}
                      scale={0.637}
                    >
                      <group name="New_Petal_7_4">
                        <mesh
                          name="New_Petal_7_4__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_4__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_3"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_5"
                      position={[0, 0, -7]}
                      rotation={[0.008, -0.017, -0.262]}
                      scale={0.851}
                    >
                      <group name="New_Petal_0_6">
                        <mesh
                          name="New_Petal_0_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_5"
                      position={[4.95, 0, -4.95]}
                      rotation={[0.012, -0.803, -0.253]}
                      scale={0.851}
                    >
                      <group name="New_Petal_1_6">
                        <mesh
                          name="New_Petal_1_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_5"
                      position={[7, 0, 0]}
                      rotation={[2.69, -1.551, 2.429]}
                      scale={0.851}
                    >
                      <group name="New_Petal_2_6">
                        <mesh
                          name="New_Petal_2_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_5"
                      position={[4.95, 0, 4.95]}
                      rotation={[3.13, -0.768, 2.872]}
                      scale={0.851}
                    >
                      <group name="New_Petal_3_6">
                        <mesh
                          name="New_Petal_3_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_5"
                      position={[0, 0, 7]}
                      rotation={[3.133, 0.017, 2.88]}
                      scale={0.851}
                    >
                      <group name="New_Petal_4_6">
                        <mesh
                          name="New_Petal_4_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_5"
                      position={[-4.95, 0, 4.95]}
                      rotation={[3.129, 0.803, 2.889]}
                      scale={0.851}
                    >
                      <group name="New_Petal_5_6">
                        <mesh
                          name="New_Petal_5_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_5"
                      position={[-7, 0, 0]}
                      rotation={[0.451, 1.551, -0.713]}
                      scale={0.851}
                    >
                      <group name="New_Petal_6_6">
                        <mesh
                          name="New_Petal_6_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_5"
                      position={[-4.95, 0, -4.95]}
                      rotation={[0.012, 0.768, -0.27]}
                      scale={0.851}
                    >
                      <group name="New_Petal_7_6">
                        <mesh
                          name="New_Petal_7_6__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_6__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_4"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_7"
                      position={[0, 0, -7]}
                      rotation={[0.695, -0.013, -0.251]}
                      scale={0.964}
                    >
                      <group name="New_Petal_0_8">
                        <mesh
                          name="New_Petal_0_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_7"
                      position={[4.95, 0, -4.95]}
                      rotation={[0.876, -0.586, 0.323]}
                      scale={0.964}
                    >
                      <group name="New_Petal_1_8">
                        <mesh
                          name="New_Petal_1_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_7"
                      position={[7, 0, 0]}
                      rotation={[1.592, -0.876, 1.336]}
                      scale={0.964}
                    >
                      <group name="New_Petal_2_8">
                        <mesh
                          name="New_Petal_2_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_7"
                      position={[4.95, 0, 4.95]}
                      rotation={[2.283, -0.563, 2.326]}
                      scale={0.964}
                    >
                      <group name="New_Petal_3_8">
                        <mesh
                          name="New_Petal_3_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_7"
                      position={[0, 0, 7]}
                      rotation={[2.447, 0.013, 2.891]}
                      scale={0.964}
                    >
                      <group name="New_Petal_4_8">
                        <mesh
                          name="New_Petal_4_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_7"
                      position={[-4.95, 0, 4.95]}
                      rotation={[2.266, 0.586, -2.818]}
                      scale={0.964}
                    >
                      <group name="New_Petal_5_8">
                        <mesh
                          name="New_Petal_5_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_7"
                      position={[-7, 0, 0]}
                      rotation={[1.55, 0.876, -1.805]}
                      scale={0.964}
                    >
                      <group name="New_Petal_6_8">
                        <mesh
                          name="New_Petal_6_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_7"
                      position={[-4.95, 0, -4.95]}
                      rotation={[0.858, 0.563, -0.815]}
                      scale={0.964}
                    >
                      <group name="New_Petal_7_8">
                        <mesh
                          name="New_Petal_7_8__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_8__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_5"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_9"
                      position={[0, 0, -7]}
                      rotation={[1.578, 0, -0.244]}
                      scale={0.122}
                    >
                      <group name="New_Petal_0_10">
                        <mesh
                          name="New_Petal_0_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_9"
                      position={[4.95, 0, -4.95]}
                      rotation={[1.576, 0.005, 0.541]}
                      scale={0.122}
                    >
                      <group name="New_Petal_1_10">
                        <mesh
                          name="New_Petal_1_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_9"
                      position={[7, 0, 0]}
                      rotation={[1.571, 0.007, 1.326]}
                      scale={0.122}
                    >
                      <group name="New_Petal_2_10">
                        <mesh
                          name="New_Petal_2_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_9"
                      position={[4.95, 0, 4.95]}
                      rotation={[1.566, 0.005, 2.112]}
                      scale={0.122}
                    >
                      <group name="New_Petal_3_10">
                        <mesh
                          name="New_Petal_3_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_9"
                      position={[0, 0, 7]}
                      rotation={[1.564, 0, 2.897]}
                      scale={0.122}
                    >
                      <group name="New_Petal_4_10">
                        <mesh
                          name="New_Petal_4_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_9"
                      position={[-4.95, 0, 4.95]}
                      rotation={[1.566, -0.005, -2.601]}
                      scale={0.122}
                    >
                      <group name="New_Petal_5_10">
                        <mesh
                          name="New_Petal_5_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_9"
                      position={[-7, 0, 0]}
                      rotation={[1.571, -0.007, -1.815]}
                      scale={0.122}
                    >
                      <group name="New_Petal_6_10">
                        <mesh
                          name="New_Petal_6_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_9"
                      position={[-4.95, 0, -4.95]}
                      rotation={[1.576, -0.005, -1.03]}
                      scale={0.122}
                    >
                      <group name="New_Petal_7_10">
                        <mesh
                          name="New_Petal_7_10__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_10__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_6"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_11"
                      position={[0, 0, -7]}
                      rotation={[1.578, 0, -0.244]}
                      scale={0.122}
                    >
                      <group name="New_Petal_0_12">
                        <mesh
                          name="New_Petal_0_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_11"
                      position={[4.95, 0, -4.95]}
                      rotation={[1.576, 0.005, 0.541]}
                      scale={0.122}
                    >
                      <group name="New_Petal_1_12">
                        <mesh
                          name="New_Petal_1_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_11"
                      position={[7, 0, 0]}
                      rotation={[1.571, 0.007, 1.326]}
                      scale={0.122}
                    >
                      <group name="New_Petal_2_12">
                        <mesh
                          name="New_Petal_2_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_11"
                      position={[4.95, 0, 4.95]}
                      rotation={[1.566, 0.005, 2.112]}
                      scale={0.122}
                    >
                      <group name="New_Petal_3_12">
                        <mesh
                          name="New_Petal_3_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_11"
                      position={[0, 0, 7]}
                      rotation={[1.564, 0, 2.897]}
                      scale={0.122}
                    >
                      <group name="New_Petal_4_12">
                        <mesh
                          name="New_Petal_4_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_11"
                      position={[-4.95, 0, 4.95]}
                      rotation={[1.566, -0.005, -2.601]}
                      scale={0.122}
                    >
                      <group name="New_Petal_5_12">
                        <mesh
                          name="New_Petal_5_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_11"
                      position={[-7, 0, 0]}
                      rotation={[1.571, -0.007, -1.815]}
                      scale={0.122}
                    >
                      <group name="New_Petal_6_12">
                        <mesh
                          name="New_Petal_6_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_11"
                      position={[-4.95, 0, -4.95]}
                      rotation={[1.576, -0.005, -1.03]}
                      scale={0.122}
                    >
                      <group name="New_Petal_7_12">
                        <mesh
                          name="New_Petal_7_12__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_12__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_7"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_13"
                      position={[0, 0, -7]}
                      rotation={[2.278, 0.011, -0.249]}
                      scale={0.1}
                    >
                      <group name="New_Petal_0_14">
                        <mesh
                          name="New_Petal_0_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_13"
                      position={[4.95, 0, -4.95]}
                      rotation={[2.107, 0.487, 0.405]}
                      scale={0.1}
                    >
                      <group name="New_Petal_1_14">
                        <mesh
                          name="New_Petal_1_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_13"
                      position={[7, 0, 0]}
                      rotation={[1.556, 0.708, 1.332]}
                      scale={0.1}
                    >
                      <group name="New_Petal_2_14">
                        <mesh
                          name="New_Petal_2_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_13"
                      position={[4.95, 0, 4.95]}
                      rotation={[1.019, 0.469, 2.247]}
                      scale={0.1}
                    >
                      <group name="New_Petal_3_14">
                        <mesh
                          name="New_Petal_3_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_13"
                      position={[0, 0, 7]}
                      rotation={[0.863, -0.011, 2.893]}
                      scale={0.1}
                    >
                      <group name="New_Petal_4_14">
                        <mesh
                          name="New_Petal_4_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_13"
                      position={[-4.95, 0, 4.95]}
                      rotation={[1.035, -0.487, -2.737]}
                      scale={0.1}
                    >
                      <group name="New_Petal_5_14">
                        <mesh
                          name="New_Petal_5_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_13"
                      position={[-7, 0, 0]}
                      rotation={[1.586, -0.708, -1.81]}
                      scale={0.1}
                    >
                      <group name="New_Petal_6_14">
                        <mesh
                          name="New_Petal_6_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_13"
                      position={[-4.95, 0, -4.95]}
                      rotation={[2.122, -0.469, -0.895]}
                      scale={0.1}
                    >
                      <group name="New_Petal_7_14">
                        <mesh
                          name="New_Petal_7_14__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_14__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_8"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_15"
                      position={[0, 0, -7]}
                      rotation={[3.017, 0.017, -0.26]}
                      scale={0.1}
                    >
                      <group name="New_Petal_0_16">
                        <mesh
                          name="New_Petal_0_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_15"
                      position={[4.95, 0, -4.95]}
                      rotation={[2.964, 0.795, -0.134]}
                      scale={0.1}
                    >
                      <group name="New_Petal_1_16">
                        <mesh
                          name="New_Petal_1_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_15"
                      position={[7, 0, 0]}
                      rotation={[1.432, 1.445, 1.449]}
                      scale={0.1}
                    >
                      <group name="New_Petal_2_16">
                        <mesh
                          name="New_Petal_2_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_15"
                      position={[4.95, 0, 4.95]}
                      rotation={[0.172, 0.761, 2.761]}
                      scale={0.1}
                    >
                      <group name="New_Petal_3_16">
                        <mesh
                          name="New_Petal_3_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_15"
                      position={[0, 0, 7]}
                      rotation={[0.124, -0.017, 2.882]}
                      scale={0.1}
                    >
                      <group name="New_Petal_4_16">
                        <mesh
                          name="New_Petal_4_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_15"
                      position={[-4.95, 0, 4.95]}
                      rotation={[0.178, -0.795, 3.007]}
                      scale={0.1}
                    >
                      <group name="New_Petal_5_16">
                        <mesh
                          name="New_Petal_5_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_15"
                      position={[-7, 0, 0]}
                      rotation={[1.71, -1.445, -1.693]}
                      scale={0.1}
                    >
                      <group name="New_Petal_6_16">
                        <mesh
                          name="New_Petal_6_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_15"
                      position={[-4.95, 0, -4.95]}
                      rotation={[2.97, -0.761, -0.381]}
                      scale={0.1}
                    >
                      <group name="New_Petal_7_16">
                        <mesh
                          name="New_Petal_7_16__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_16__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_9"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_17"
                      position={[0, 0, -7]}
                      rotation={[-2.712, 0.016, -0.269]}
                      scale={0.1}
                    >
                      <group name="New_Petal_0_18">
                        <mesh
                          name="New_Petal_0_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_17"
                      position={[4.95, 0, -4.95]}
                      rotation={[-2.559, 0.713, -0.669]}
                      scale={0.1}
                    >
                      <group name="New_Petal_1_18">
                        <mesh
                          name="New_Petal_1_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_17"
                      position={[7, 0, 0]}
                      rotation={[-1.533, 1.141, -1.874]}
                      scale={0.1}
                    >
                      <group name="New_Petal_2_18">
                        <mesh
                          name="New_Petal_2_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_17"
                      position={[4.95, 0, 4.95]}
                      rotation={[-0.567, 0.684, -3.021]}
                      scale={0.1}
                    >
                      <group name="New_Petal_3_18">
                        <mesh
                          name="New_Petal_3_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_17"
                      position={[0, 0, 7]}
                      rotation={[-0.429, -0.016, 2.873]}
                      scale={0.1}
                    >
                      <group name="New_Petal_4_18">
                        <mesh
                          name="New_Petal_4_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_17"
                      position={[-4.95, 0, 4.95]}
                      rotation={[-0.583, -0.713, 2.473]}
                      scale={0.1}
                    >
                      <group name="New_Petal_5_18">
                        <mesh
                          name="New_Petal_5_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_17"
                      position={[-7, 0, 0]}
                      rotation={[-1.609, -1.141, 1.267]}
                      scale={0.1}
                    >
                      <group name="New_Petal_6_18">
                        <mesh
                          name="New_Petal_6_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_17"
                      position={[-4.95, 0, -4.95]}
                      rotation={[-2.575, -0.684, 0.12]}
                      scale={0.1}
                    >
                      <group name="New_Petal_7_18">
                        <mesh
                          name="New_Petal_7_18__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_18__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="Cloner_10"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_19"
                      position={[0, 0, -7]}
                      rotation={[-2.257, 0.011, -0.275]}
                      scale={0.1}
                    >
                      <group name="New_Petal_0_20">
                        <mesh
                          name="New_Petal_0_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_0_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_1_19"
                      position={[4.95, 0, -4.95]}
                      rotation={[-2.088, 0.473, -0.937]}
                      scale={0.1}
                    >
                      <group name="New_Petal_1_20">
                        <mesh
                          name="New_Petal_1_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_1_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_2_19"
                      position={[7, 0, 0]}
                      rotation={[-1.557, 0.686, -1.855]}
                      scale={0.1}
                    >
                      <group name="New_Petal_2_20">
                        <mesh
                          name="New_Petal_2_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_2_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_3_19"
                      position={[4.95, 0, 4.95]}
                      rotation={[-1.039, 0.456, -2.762]}
                      scale={0.1}
                    >
                      <group name="New_Petal_3_20">
                        <mesh
                          name="New_Petal_3_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_3_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_4_19"
                      position={[0, 0, 7]}
                      rotation={[-0.885, -0.011, 2.866]}
                      scale={0.1}
                    >
                      <group name="New_Petal_4_20">
                        <mesh
                          name="New_Petal_4_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_4_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_5_19"
                      position={[-4.95, 0, 4.95]}
                      rotation={[-1.054, -0.473, 2.204]}
                      scale={0.1}
                    >
                      <group name="New_Petal_5_20">
                        <mesh
                          name="New_Petal_5_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_5_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_6_19"
                      position={[-7, 0, 0]}
                      rotation={[-1.585, -0.686, 1.286]}
                      scale={0.1}
                    >
                      <group name="New_Petal_6_20">
                        <mesh
                          name="New_Petal_6_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_6_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                    <group
                      name="New_Petal_7_19"
                      position={[-4.95, 0, -4.95]}
                      rotation={[-2.103, -0.456, 0.38]}
                      scale={0.1}
                    >
                      <group name="New_Petal_7_20">
                        <mesh
                          name="New_Petal_7_20__0"
                          castShadow
                          receiveShadow
                          geometry={nodes.New_Petal_7_20__0.geometry}
                          material={materials["Scene_-_Root"]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Lotus">
                  <group
                    name="Inner"
                    position={[0, 10.019, 0]}
                    rotation={[0, -Math.PI / 9, 0]}
                  >
                    <group
                      name="New_Petal_0_21"
                      position={[0, 0, -7]}
                      rotation={[0.855, -0.011, -0.249]}
                    >
                      <group name="New_Petal_0_22" />
                    </group>
                    <group
                      name="New_Petal_1_21"
                      position={[4.95, 0, -4.95]}
                      rotation={[1.028, -0.491, 0.402]}
                    >
                      <group name="New_Petal_1_22" />
                    </group>
                    <group
                      name="New_Petal_2_21"
                      position={[7, 0, 0]}
                      rotation={[1.586, -0.715, 1.332]}
                    >
                      <group name="New_Petal_2_22" />
                    </group>
                    <group
                      name="New_Petal_3_21"
                      position={[4.95, 0, 4.95]}
                      rotation={[2.13, -0.473, 2.25]}
                    >
                      <group name="New_Petal_3_22" />
                    </group>
                    <group
                      name="New_Petal_4_21"
                      position={[0, 0, 7]}
                      rotation={[2.286, 0.011, 2.893]}
                    >
                      <group name="New_Petal_4_22" />
                    </group>
                    <group
                      name="New_Petal_5_21"
                      position={[-4.95, 0, 4.95]}
                      rotation={[2.114, 0.491, -2.74]}
                    >
                      <group name="New_Petal_5_22" />
                    </group>
                    <group
                      name="New_Petal_6_21"
                      position={[-7, 0, 0]}
                      rotation={[1.556, 0.715, -1.809]}
                    >
                      <group name="New_Petal_6_22" />
                    </group>
                    <group
                      name="New_Petal_7_21"
                      position={[-4.95, 0, -4.95]}
                      rotation={[1.012, 0.473, -0.892]}
                    >
                      <group name="New_Petal_7_22" />
                    </group>
                  </group>
                  <group name="Middle" rotation={[0, -Math.PI / 9, 0]}>
                    <group
                      name="New_Petal_0_23"
                      position={[0, 0, -23]}
                      rotation={[0.768, -0.013, -0.197]}
                    >
                      <group name="New_Petal_0_24" />
                    </group>
                    <group
                      name="New_Petal_1_23"
                      position={[19.919, 0, -11.5]}
                      rotation={[1.106, -0.68, 0.688]}
                    >
                      <group name="New_Petal_1_24" />
                    </group>
                    <group
                      name="New_Petal_2_23"
                      position={[19.919, 0, 11.5]}
                      rotation={[2.061, -0.664, 2.074]}
                    >
                      <group name="New_Petal_2_24" />
                    </group>
                    <group
                      name="New_Petal_3_23"
                      position={[0, 0, 23]}
                      rotation={[2.374, 0.013, 2.944]}
                    >
                      <group name="New_Petal_3_24" />
                    </group>
                    <group
                      name="New_Petal_4_23"
                      position={[-19.919, 0, 11.5]}
                      rotation={[2.036, 0.68, -2.454]}
                    >
                      <group name="New_Petal_4_24" />
                    </group>
                    <group
                      name="New_Petal_5_23"
                      position={[-19.919, 0, -11.5]}
                      rotation={[1.081, 0.664, -1.067]}
                    >
                      <group name="New_Petal_5_24" />
                    </group>
                  </group>
                  <group name="Outer" position={[0, 2.847, 0]}>
                    <group
                      name="New_Petal_0_25"
                      position={[0, 0, -27]}
                      rotation={[0.646, -0.014, -0.199]}
                    >
                      <group name="New_Petal_0_26" />
                    </group>
                    <group
                      name="New_Petal_1_25"
                      position={[11.715, 0, -24.326]}
                      rotation={[0.701, -0.367, 0.085]}
                    >
                      <group name="New_Petal_1_26" />
                    </group>
                    <group
                      name="New_Petal_2_25"
                      position={[21.109, 0, -16.834]}
                      rotation={[0.89, -0.685, 0.454]}
                    >
                      <group name="New_Petal_2_26" />
                    </group>
                    <group
                      name="New_Petal_3_25"
                      position={[26.323, 0, -6.008]}
                      rotation={[1.305, -0.897, 1.026]}
                    >
                      <group name="New_Petal_3_26" />
                    </group>
                    <group
                      name="New_Petal_4_25"
                      position={[26.323, 0, 6.008]}
                      rotation={[1.879, -0.887, 1.75]}
                    >
                      <group name="New_Petal_4_26" />
                    </group>
                    <group
                      name="New_Petal_5_25"
                      position={[21.109, 0, 16.834]}
                      rotation={[2.273, -0.663, 2.303]}
                    >
                      <group name="New_Petal_5_26" />
                    </group>
                    <group
                      name="New_Petal_6_23"
                      position={[11.715, 0, 24.326]}
                      rotation={[2.449, -0.34, 2.662]}
                    >
                      <group name="New_Petal_6_24" />
                    </group>
                    <group
                      name="New_Petal_7_23"
                      position={[0, 0, 27]}
                      rotation={[2.496, 0.014, 2.943]}
                    >
                      <group name="New_Petal_7_24" />
                    </group>
                    <group
                      name="New_Petal_8"
                      position={[-11.715, 0, 24.326]}
                      rotation={[2.441, 0.367, -3.057]}
                    >
                      <group name="New_Petal_8_2" />
                    </group>
                    <group
                      name="New_Petal_9"
                      position={[-21.109, 0, 16.834]}
                      rotation={[2.251, 0.685, -2.687]}
                    >
                      <group name="New_Petal_9_2" />
                    </group>
                    <group
                      name="New_Petal_10"
                      position={[-26.323, 0, 6.008]}
                      rotation={[1.837, 0.897, -2.116]}
                    >
                      <group name="New_Petal_10_2" />
                    </group>
                    <group
                      name="New_Petal_11"
                      position={[-26.323, 0, -6.008]}
                      rotation={[1.263, 0.887, -1.391]}
                    >
                      <group name="New_Petal_11_2" />
                    </group>
                    <group
                      name="New_Petal_12"
                      position={[-21.109, 0, -16.834]}
                      rotation={[0.869, 0.663, -0.839]}
                    >
                      <group name="New_Petal_12_2" />
                    </group>
                    <group
                      name="New_Petal_13"
                      position={[-11.715, 0, -24.326]}
                      rotation={[0.692, 0.34, -0.48]}
                    >
                      <group name="New_Petal_13_2" />
                    </group>
                  </group>
                  <group name="Outer_1" position={[0, 2.847, 0]}>
                    <group
                      name="New_Petal_0_27"
                      position={[0, 0, -27]}
                      rotation={[0.07, -0.017, -0.208]}
                    >
                      <group name="New_Petal_0_28" />
                    </group>
                    <group
                      name="New_Petal_1_27"
                      position={[21.109, 0, -16.834]}
                      rotation={[0.114, -0.912, -0.119]}
                    >
                      <group name="New_Petal_1_28" />
                    </group>
                    <group
                      name="New_Petal_2_27"
                      position={[26.323, 0, 6.008]}
                      rotation={[2.858, -1.319, 2.657]}
                    >
                      <group name="New_Petal_2_28" />
                    </group>
                    <group
                      name="New_Petal_3_27"
                      position={[11.715, 0, 24.326]}
                      rotation={[3.065, -0.43, 2.9]}
                    >
                      <group name="New_Petal_3_28" />
                    </group>
                    <group
                      name="New_Petal_4_27"
                      position={[-11.715, 0, 24.326]}
                      rotation={[3.063, 0.465, 2.967]}
                    >
                      <group name="New_Petal_4_28" />
                    </group>
                    <group
                      name="New_Petal_5_27"
                      position={[-26.323, 0, 6.008]}
                      rotation={[2.814, 1.353, -3.03]}
                    >
                      <group name="New_Petal_5_28" />
                    </group>
                    <group
                      name="New_Petal_6_25"
                      position={[-21.109, 0, -16.834]}
                      rotation={[0.109, 0.877, -0.294]}
                    >
                      <group name="New_Petal_6_26" />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(model);