/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kyuukonneko (https://sketchfab.com/kyuukonneko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/envelope-46acaf7efc054eae9712e277a501f15c
Title: Envelope
*/

import React, { useEffect, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

import model from "../../assets/cottage/envelope.glb";

export function Envelope({ position = [0, 0, 0], scale = 0.3, makePotion = false }) {
    const { nodes, materials } = useGLTF(model);
    const ref = useRef();
    const tl = new gsap.timeline({
        defaults: { duration: 1.2, delay: 0.05 } 
    });

    useEffect(() => {
        if(makePotion) {
            tl.to(ref.current.position, {
                x: 30,
                y: -28,
                z: 18
            });
            // tl.to(ref.current.scale, {
            //     x: ref.current.scale.x * 1.2,
            //     y: ref.current.scale.y * 1.2,
            //     z: ref.current.scale.z * 1.2
            // });
        }
    }, [makePotion]);

    useFrame(() => {
        ref.current.rotation.y += 0.003;
    })

    return (
        <group position={position} scale={scale} ref={ref} dispose={null}>
            <group scale={0.025}>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box002_paper_0.geometry}
                material={materials.paper}
                position={[0, -0.9, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box003_up_paper_0.geometry}
                material={materials.up_paper}
                position={[0.028, -0.5, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box004_up_paper_0.geometry}
                material={materials.up_paper}
                position={[-0.028, -0.5, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box006_ribbon_0.geometry}
                material={materials.ribbon}
                position={[-4.186, 0.1, 4.396]}
                rotation={[-Math.PI / 2, 0, Math.PI / 4]}
                scale={[0.603, 0.603, 1.184]}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_batch_0.geometry}
                material={materials.batch}
                position={[0, 0.1, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                />
            </group>
        </group>
    );
}

useGLTF.preload(model);
