/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OkameMiko (https://sketchfab.com/OkameMiko)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/fourseasonsgriffons-spring-8351dac788d141ef85317d54b589cd9a
Title: FourSeasonsGriffons Spring
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import model from "../../assets/cottage/fourseasonsgriffons_spring.glb";

export function GriffonSpring(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(model);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="haru_anmfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="group1" position={[0, 0, -96.8]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_95"
                      geometry={nodes.Object_95.geometry}
                      material={materials.Spring_exportharu_body_mat}
                      skeleton={nodes.Object_95.skeleton}
                    />
                    <skinnedMesh
                      name="Object_97"
                      geometry={nodes.Object_97.geometry}
                      material={materials.Spring_exportharu_horn_alpha_mat}
                      skeleton={nodes.Object_97.skeleton}
                    />
                    <skinnedMesh
                      name="Object_98"
                      geometry={nodes.Object_98.geometry}
                      material={materials.Spring_exportharu_horn_mat}
                      skeleton={nodes.Object_98.skeleton}
                    />
                    <skinnedMesh
                      name="Object_100"
                      geometry={nodes.Object_100.geometry}
                      material={materials.Spring_exportharu_body_mat}
                      skeleton={nodes.Object_100.skeleton}
                    />
                    <skinnedMesh
                      name="Object_102"
                      geometry={nodes.Object_102.geometry}
                      material={materials.Spring_exportharu_eye_mat}
                      skeleton={nodes.Object_102.skeleton}
                    />
                    <skinnedMesh
                      name="Object_104"
                      geometry={nodes.Object_104.geometry}
                      material={materials.Spring_exportharu_eye_mat}
                      skeleton={nodes.Object_104.skeleton}
                    />
                    <group name="Object_94" />
                    <group name="Object_96" />
                    <group name="Object_99" />
                    <group name="Object_101" />
                    <group name="Object_103" />
                  </group>
                </group>
                <group name="Spring_exportSpring_mdl">
                  <group name="Spring_exportHaru_body" />
                  <group name="Spring_exportHaru_horn" />
                  <group name="Spring_exportHaru_tail" />
                  <group name="Spring_exportHaru_eye_00">
                    <group name="Spring_exportHaru_eye_01" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(model);