/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OkameMiko (https://sketchfab.com/OkameMiko)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/littlegriffons-hollandicus01-50689678e0de46d7ae9f58e0aa87db4e
Title: LittleGriffons hollandicus01
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import model from "../../assets/cottage/littlegriffons_hollandicus01.glb";

export function Griffon(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    model
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Take 001"].play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Okame_01fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.hollandicus_01_exportoutline_01}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.hollandicus_01_exportm_hollandicus_01}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <group name="Object_6" />
                  <group name="hollandicus_01_exporthollandicus_mdl" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(model);