/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Pixel Life (https://sketchfab.com/pixellife)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/potion-poison-elixir-game-ready-asset-d6922ab35d474c7e9c3e12c9e684bcf1
Title: Potion Poison Elixir (game ready asset)
*/

import React, { useEffect, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

import model from "../../assets/cottage/strength_poison.glb";

export function StrengthPotion({ handleResumeDialog, completePotion, position = [0, 0, 0], scale = 0.3, makePotion = false }) {
    const { nodes, materials } = useGLTF(model);
    const ref = useRef();
    const tl = new gsap.timeline({
        defaults: { duration: 1.2, delay: 0.05 } 
    });

    useEffect(() => {
        if(makePotion) {
            tl.to(ref.current.position, {
                x: 25,
                y: -20,
                z: 18
            });
            // tl.to(ref.current.scale, {
            //     x: ref.current.scale.x * 1.2,
            //     y: ref.current.scale.y * 1.2,
            //     z: ref.current.scale.z * 1.2
            // });
            setTimeout(() => {
                handleResumeDialog();
                completePotion();
            }, 2000);
        }
    }, [makePotion]);

    useFrame(() => {
        ref.current.rotation.y += 0.003;
    })

    return (
        <group position={position} scale={scale} ref={ref} dispose={null}>
            <group>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.Potion}
                />
            </group>
        </group>
    );
}

useGLTF.preload(model);